# Generated by Django 4.1.7 on 2023-04-08 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notesmodel',
            name='text',
            field=models.CharField(max_length=2048),
        ),
    ]
